const $=id=>document.getElementById(id);
const read=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
const save=(key,value)=>{try{localStorage.setItem(key,value);}catch{}};
let group=Number(read('k13-group','1'));if(![1,2].includes(group))group=1;
let endpoint=window.K13_CONFIG.alertEndpoint,alertState=null,checkedAt=0,lastChecked=0,pending=false;
function kyiv(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}:${p.second}`,minute:Number(p.hour)*60+Number(p.minute)};}
function inSemester(date){return date>=K13_CONFIG.semesterStart&&date<=K13_CONFIG.semesterEnd;}
function list(date){return inSemester(date)?lessons(date,group):[];}
function renderSchedule(){const date=$('scheduleDate').value,k=kyiv();$('dayCaption').textContent=`${new Date(date+'T12:00:00Z').toLocaleDateString('uk-UA',{weekday:'long',day:'numeric',month:'long'})} · ${parity(date)==='even'?'парний':'непарний'} тиждень · підгрупа ${group}`;const rows=list(date);$('lessons').replaceChildren();if(!rows.length){$('lessons').textContent=inSemester(date)?'Цього дня для твоєї підгрупи пар немає.':'Дата поза налаштованими межами семестру.';return;}for(const l of rows){const el=document.createElement('div');el.className='lesson'+(date===k.date&&k.minute>=minutes(l.start)&&k.minute<minutes(l.end)?' current':'');const time=document.createElement('time');time.textContent=`${l.start}–${l.end}`;const body=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small');title.textContent=l.title;meta.textContent=`${l.slot} пара · ${l.type} · ${l.teacher}`;body.append(title,meta);el.append(time,body);$('lessons').append(el);}}
function render(){const k=kyiv(),rows=list(k.date),current=rows.find(l=>k.minute>=minutes(l.start)&&k.minute<minutes(l.end)),next=rows.find(l=>minutes(l.start)>k.minute);$('clock').textContent=k.time;$('date').textContent=new Date().toLocaleDateString('uk-UA',{timeZone:'Europe/Kyiv',weekday:'short',day:'numeric',month:'long'});$('parity').textContent=(parity(k.date)==='even'?'Парний':'Непарний')+' тиждень';const state=Date.now()-checkedAt<90000?alertState:null;let cls='idle',title='Зараз пар немає',label='ВІЛЬНИЙ ЧАС';if(current){label='ЗАРАЗ ЗА РОЗКЛАДОМ';if(state===true){cls='alert';title='Заняття призупинено';}else if(state===false){cls='active';title='Зараз у тебе пара';}else{cls='unknown';title='За розкладом зараз пара';}}
if(state===true){cls='alert';label='ПОВІТРЯНА ТРИВОГА · КИЇВ';if(!current)title='Тривога. Зараз пар немає';}
$('status').className='status '+cls;$('statusLabel').textContent=label;$('statusTitle').textContent=title;$('subject').textContent=current?`${current.title} · ${current.teacher} · ${current.start}–${current.end}`:next?`Наступна: ${next.title} о ${next.start}`:inSemester(k.date)?'Заняття на сьогодні завершено або не заплановані.':'Дата поза налаштованими межами семестру.';$('countdown').textContent=current?(state===true?'Повернися після відбою, якщо час пари ще триває.':state===null?'Статус тривоги невідомий. Перевір офіційні повідомлення.':`До кінця пари ${minutes(current.end)-k.minute} хв.`):next?`До наступної пари ${minutes(next.start)-k.minute} хв.`:'';
$('alertText').textContent=state===true?'🔴 У Києві повітряна тривога':state===false?'🟢 За даними сервісу тривоги немає':'🟠 Статус тривоги невідомий';$('alertTime').textContent=lastChecked?'Остання успішна перевірка: '+new Date(lastChecked).toLocaleTimeString('uk-UA',{timeZone:'Europe/Kyiv'}):endpoint?'Очікуємо відповідь сервісу':'Джерело ще не підключено';document.querySelectorAll('[data-group]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.group)===group);b.setAttribute('aria-pressed',String(Number(b.dataset.group)===group));});}
async function updateAlert(){if(!endpoint||pending)return;pending=true;try{const response=await fetch(endpoint,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error();const data=await response.json(),stamp=Date.parse(data.checkedAt);if(typeof data.active!=='boolean'||!Number.isFinite(stamp)||Date.now()-stamp>90000||stamp>Date.now()+10000)throw Error();alertState=data.active;checkedAt=stamp;lastChecked=stamp;}catch{alertState=null;checkedAt=0;}finally{pending=false;render();}}
async function weather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=50.45&longitude=30.52&current=temperature_2m,apparent_temperature,wind_speed_10m&hourly=precipitation_probability&forecast_days=2&timezone=Europe%2FKyiv',{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const d=await r.json(),c=d.current;if(!Number.isFinite(c.temperature_2m)||!Number.isFinite(c.apparent_temperature))throw Error();const k=kyiv(),prefix=k.date+'T'+k.time.slice(0,2),idx=d.hourly.time.findIndex(t=>t.startsWith(prefix)),rain=idx<0?null:Math.max(...d.hourly.precipitation_probability.slice(idx,idx+3));$('weather').textContent=`${Math.round(c.temperature_2m)}° · відчувається як ${Math.round(c.apparent_temperature)}°`;$('outfit').textContent=(c.apparent_temperature<5?'Тепла куртка та закрите взуття.':c.apparent_temperature<15?'Куртка або светр.':c.apparent_temperature<23?'Легка кофта стане в пригоді.':'Легкий одяг.')+(rain!==null&&rain>=40?' Візьми парасольку.':'')+` Вітер ${Math.round(c.wind_speed_10m)} км/год.`;$('weatherTime').textContent=`Дані прогнозу: ${c.time.replace('T',' ')} · опади найближчі 3 год: ${rain===null?'немає даних':rain+'%'}`;}catch{$('weather').textContent='Погода недоступна';$('outfit').textContent='Не вдалося оновити прогноз.';$('weatherTime').textContent='Спробуємо знову під час наступного оновлення.';}}
$('scheduleDate').value=kyiv().date;$('scheduleDate').addEventListener('change',()=>{if($('scheduleDate').value)renderSchedule();});document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{group=Number(b.dataset.group);save('k13-group',String(group));render();renderSchedule();}));document.addEventListener('visibilitychange',()=>{if(!document.hidden){render();renderSchedule();updateAlert();weather();}});render();renderSchedule();updateAlert();weather();let prior=kyiv().date;setInterval(()=>{const date=kyiv().date;if(date!==prior){if($('scheduleDate').value===prior)$('scheduleDate').value=date;prior=date;}render();renderSchedule();},1000);setInterval(updateAlert,30000);setInterval(weather,900000);
